use safe_load instead of load
workaround for TypeError: load() missing 1 required positional argument: 'Loader' Please check https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation